version: '3'
services:
  cahbackend:
    build:
      context: .
      dockerfile: lib_webserver/Dockerfile
    container_name: cah_backend
    ports:
      - 4040:4040
  cahbotservice:
    build:
      context: .
      dockerfile: lib_bot/Dockerfile
    container_name: cah_bot_service
    ports:
      - 4041:4041
    depends_on:
      - cahbackend
  cahfrontend:
    container_name: cah_frontend
    ports:
      - 5000:80
    image: nginx
    # build: .
    volumes:
      - ./build/web:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - cahbackend
      - cahbotservice