name: projectcahfungame
description: A new Flutter application.

version: 0.1.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  howler: ^1.0.7
  flutter_icons: ^1.0.0+1
  shared_preferences: ^0.5.6+3
#  uuid: ^2.0.4
 # colorize: ^2.0.0
  url_launcher: ^5.4.7
  cah_common_values:
    path: ../lib_common

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
     - audio/win.mp3
     - gamerules.json